version: "3"
services:
    feeds:
        image: rotten
        build: ./dockerfiles/servicos/
        hostname: feeds
        volumes:
            - './feeds:/servico'
        command: python3 servico.py
        ports:
            - '5010:5000'
        
    detalhes:
        image: rotten
        build: ./dockerfiles/servicos/
        hostname: detalhes
        volumes:
            - './detalhes:/servico'
        command: python3 servico.py
        ports:
            - '5011:5000'
        
    bancodados:
        image: mysql
        hostname: bancodados
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - '5012:3306'

    arquivos:
        image: arquivos
        build: ./dockerfiles/nginx
        volumes: 
            - './assets/imagens:/usr/share/nginx/html'
        hostname: "arquivos"
        ports:
            - '5013:80'
